version: "3"
services:
  shadowsocks:
    image: shadowsocks/shadowsocks-libev
    ports:
      - "29499:8388/tcp"
      - "29499:8388/udp"
    environment:
      - METHOD=aes-256-gcm
      - PASSWORD=poiu)(*&
    restart: always