version: "3"
services:
  redis:
    image: chrdw/redis:1.0.0
    hostname: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
    - /home/chrdw/dev/redis/data:/data
    restart: always
    networks:
      - redis_default
networks:
  redis_default:
    driver: bridge